# Project-wide Gradle settings.
# Detalle: https://docs.gradle.org/current/userguide/build_environment.html

# JVM options para el demonio de Gradle.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Build paralelo entre módulos.
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false

# Kotlin
kotlin.code.style=official
ksp.useKSP2=true
